### ISSUE TITLE
ROADMAP aka. Ugly Issue collection

### ISSUE THREAD

**Issue by flowirtz** [openHPI/jenz#6]
# Moved everything to individual, better-clustered issues
- [X] Buttons oben (aka Filter) e2aa79b96f8973a3b913547861b0fdfed2b85feb
- [ ] Slider für Karte (Materialize hat einen)
- [ ] Slider bewegt sich automatisch wenn nix passiert
- [X] Pfeile bei Reviews (damit man sieht dass man nach links/rechts kann) 3f69633ba50b2524f3c892ccef50364594691fe4
- [ ] touch me! -> nutzer muss interaktivität erkennen
- [ ] m.e.i.n.e.l. für statistiken **WIP** b9887806cbf982148c2b487ceb1d73a0dcb1c8c0
- [ ] reviews in txt datei oder so auslagern
- [ ] karte: letzte 24 stunden slider, was für time-steps, wie durchscrollen, wie daten halten?
- [ ] #8
- [ ] #5

**Comment by flowirtz** [comment]
Closing issue as broken down into smaller issues.
